version: "v2.31.0-desktop.2"
services:
  backend:
    build:
      context: project1
    container_name: backend
    restart: always
    ports:
      - 8000:8000

  frontend:
    build:
      context: todo-frontend
    container_name: frontend
    restart: always
    ports:
      - 80:80